### ISSUE TITLE
Running OPC-UA commander on RaspberryPi

### ISSUE THREAD

**Issue by pablofsmelo** [node-opcua/opcua-commander#18]
Hello,

I'm running opcua-commander on my RaspberryPI, but I'm having problems. After that I installed opcua-commander, I execute the command "opcua-commander -e opc.tcp://localhost:port" and I got the following error message:

home/pi/opcua-commander/index.js:75
    throw new Error("Invalid Security mode , should be " + opcua.MessageSecurityMode.enums.join(" "));
    ^

Error: Invalid Security mode , should be INVALID NONE SIGN SIGNANDENCRYPT
    at Object.<anonymous> (/home/pi/opcua-commander/index.js:75:11)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/opcua-commander/bin/opcua-commander:3:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)

After, I adding as argument -s=NONE -P=None and the error change for this:
const client = opcua.OPCUAClient.create({
                                 ^

TypeError: opcua.OPCUAClient.create is not a function
    at Object.<anonymous> (/home/pi/opcua-commander/index.js:108:34)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)

Could someone help me with this ?

**Comment by erossignon** [comment]
same as #20
