### ISSUE TITLE
Doesn't Start

### ISSUE THREAD

**Issue by PardeepRassani** [node-opcua/opcua-commander#37]
After installing it, I am trying to run `opcua-commander`, it says:
```
/usr/local/lib/node_modules/opcua-commander/dist/model/model.js:112
    client;
          ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/opcua-commander/lib/index.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by matyas-radvanyi** [comment]
Same here 
On  Ubuntu 20.04.4 LTS + npm- 6.14.4 + node v10.19.0

**Comment by erossignon** [comment]
node v10 is not supported anymore, use node16

**Comment by erossignon** [comment]
I have downgraded javascript-generated code from ES7 to ES6 so that it works with nodejs >=12.0

Please install opcua-commander@>=0.21.0
