### ISSUE TITLE
Will not start: missing client_selfsigned_cert_1024.pem

### ISSUE THREAD

**Issue by srebling** [node-opcua/opcua-commander#7]
Install does not include client_selfsigned_cert_1024.pem.
OSX Yosemite
node v6.2.2

        throw new Error(" cannot locate certificate file "+options.certificateFile );
        ^

Error:  cannot locate certificate file /usr/local/lib/node_modules/opcua-commander/node_modules/node-opcua/certificates/client_selfsigned_cert_1024.pem
    at OPCUAClientBase (/usr/local/lib/node_modules/opcua-commander/node_modules/node-opcua/lib/client/client_base.js:68:15)
    at new OPCUAClient (/usr/local/lib/node_modules/opcua-commander/node_modules/node-opcua/lib/client/opcua_client.js:71:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/opcua-commander/index.js:91:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)

**Comment by srebling** [comment]
Used a copy of the cert file from a previous install of node-opcua. Works fine...
